import Head from 'next/head'
import Image from 'next/image'
import { Widget } from '@typeform/embed-react'
import styles from '../styles/Home.module.css'


export default function Home() {
  // <div data-tf-widget="jCNym9Oj" data-tf-hidden="name=xxxxx,refercode=xxxxx" style="width:100%;height:400px;"></div><script src="//embed.typeform.com/next/embed.js"></script>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Widget 
          id="jCNym9Oj" 
          style={{ width: '100%' }} 
          className="my-form" 
          hidden={{ name: 'Angela', refercode: 'mt5h8urij7' }}
          transitiveSearchParams={['name', 'refercode']}
          iframeProps={{ title: 'Fos Refer Form' }}
        />
      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  )
}
